### Modifier le profil admin (email seulement)
PUT http://localhost:5000/api/admin/profile
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN_HERE

{
  "email": "newemail@example.com",
  "currentPassword": "currentpassword123"
}

###

### Modifier le profil admin (mot de passe seulement)
PUT http://localhost:5000/api/admin/profile
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN_HERE

{
  "password": "newpassword123",
  "currentPassword": "currentpassword123"
}

###

### Modifier le profil admin (email, biographie, photo et réseaux sociaux)
PUT http://localhost:5000/api/admin/profile
Authorization: Bearer YOUR_JWT_TOKEN_HERE
Content-Type: multipart/form-data; boundary=---011000010111000001101001

---011000010111000001101001
Content-Disposition: form-data; name="nom"

Nom de l'auteur
---011000010111000001101001
Content-Disposition: form-data; name="email_contact"

author@example.com
---011000010111000001101001
Content-Disposition: form-data; name="message_accroche"

Texte d'accroche
---011000010111000001101001
Content-Disposition: form-data; name="biographie"

Nouvelle biographie
---011000010111000001101001
Content-Disposition: form-data; name="short_biographie"

Courte bio
---011000010111000001101001
Content-Disposition: form-data; name="socials"

[{"network":"twitter","url":"https://twitter.com/author"},{"network":"github","url":"https://github.com/author"}]
---011000010111000001101001
Content-Disposition: form-data; name="image"; filename="photo.jpg"
Content-Type: image/jpeg

< ./public/images/default_image_actus.png
---011000010111000001101001
Content-Disposition: form-data; name="currentPassword"

currentpassword123
---011000010111000001101001--